# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
    port: 8082
    
logging:
    level:
        ROOT: INFO
        vn.tcx.framework: INFO
        vn.tcx.eoffice.user: INFO
    
spring:
    profiles:
        active: prod
        #include:
        #    - swagger
            # Uncomment to activate TLS for the dev profile
            #- tls
    devtools:
        restart:
            enabled: true
    jackson:
        serialization:
            indent-output: true
    liquibase:
        enabled: false
        change-log: classpath:/migrations/master.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:oracle:thin:@192.168.1.218:1539:xe
        username: hosocongviec
        password: Tcx12345
        hikari:
            poolName: hosocongviec-pool
            auto-commit: false
    jpa:
        hibernate:
            ddl-auto: none
        # database-platform: org.hibernate.dialect.Oracle12cDialect
        # database: ORACLE
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            #hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            #hibernate.cache.hazelcast.instance_name: common
            #hibernate.cache.use_minimal_puts: true
            #hibernate.cache.hazelcast.use_lite_member: true
            
    elasticsearch:
      rest:
        uris:
        - https://es.eoffice.greenglobal.vn
        username: elastic
        password: changeme

elasticsearch:
  index:
    alias: 'qoffice_test_vanbanden'
    type: 'doc'
    shard: 3
    replica: 2
    from: 0
    size: 10
    timeout: 60

tcx:
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"

security:
  # byPassApiSecure: false
  oauth2:
    spGroup: Application/eoffice-gateway
    client: # SP eoffice-gateway
      clientId: jBVKzCkGmtlfSKW3c5nTkW_ycbsa 
      clientSecret: Knsz7AjposmGcyQ1A3Z5xURUQaUa
      
feign:
  client: #point to [gateway-host]:[gateway-port]/[service-path-defined-in-gateway]
    location: 
      gateway: https://test1-api-qn.eoffice.greenglobal.vn

