# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
    profiles:
        active: stag
        #include:
        #    - swagger
            # Uncomment to activate TLS for the dev profile
            #- tls
    kafka:
      producer:
        topics: notifications-stag
        bootstrap-servers: 10.255.35.20:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: vn.tcx.eoffice.hosocongviec.stream.NotificationSerializer
    liquibase:
        enabled: false
        change-log: classpath:/migrations/master.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:oracle:thin:@10.255.45.30:1521:xe
        username: hosocongviec
        password: Eoffqn1234
        hikari:
            poolName: hosocongviec-pool
            auto-commit: false
    jpa:
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            #hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            #hibernate.cache.hazelcast.instance_name: common
            #hibernate.cache.use_minimal_puts: true
            #hibernate.cache.hazelcast.use_lite_member: true
    elasticsearch:
      rest:
        uris:
        - http://10.255.25.11:9200
        username: elastic
        password: changeme
      index:
        alias: 'qoffice_staging_hosocongviec'
        type: 'doc'
        shard: 3
        replica: 2
        from: 0
        size: 10
        timeout: 60
      time:
        timeZoneId: 'UTC+7'

security:
  byPassApiSecure: false
  oauth2:
    spGroup: Application/eoffice-stag
    client:
      clientId: YRNBGL7NOmIuWZklZLQDnmfBvqMa
      clientSecret: 7bGWOGE8_c1RZs9JNCfINIgQaz8a
    resource:
      user-info-uri: https://sso.lgsp.quangnam.gov.vn/oauth2/userinfo?schema=openid

feign:
  client: #point to [gateway-host]:[gateway-port]/[service-path-defined-in-gateway]
    location: 
      # gateway: https://api-qoffice-staging.quangnam.gov.vn
      # file.url: file-qoffice-staging.quangnam.gov.vn/api
      gateway: http://10.255.25.11
      danh-muc.url: ${feign.client.location.gateway}:8081/danh-muc/api/client
      he-thong.url: ${feign.client.location.gateway}:8080/he-thong/api/client
      van-ban-den.url: ${feign.client.location.gateway}:8082/van-ban-den/api/client
      file.url: ${feign.client.location.gateway}:5000/api
      van-ban-di.url: ${feign.client.location.gateway}:8083/van-ban-di/api/client
      phieu-yeu-cau.url: ${feign.client.location.gateway}:8087/phieu-yeu-cau/api/client
      phieu-de-xuat.url: ${feign.client.location.gateway}:8088/phieu-de-xuat/api/client
      ky-so.url: ${feign.client.location.gateway}:8094/ky-so/api
      
tcx:
    errbit:
        host: http://10.255.35.21:8088/notifier_api/v2/notices
        id: 1
        key: a33a6380c666c772c5bfec75a8c34730
        env: stag
