server:
    port: 8080
    
logging:
    level:
        ROOT: INFO
        vn.tcx.framework: INFO
        vn.tcx.eoffice.danhmuc: INFO     
    
spring:
    application:
        name: danhmuc
    autoconfigure:
        exclude: 
            - org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration
            - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration
            - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    main:
        allow-bean-definition-overriding: true

management:
    endpoints:
        web:
            base-path: /management

tcx:
    swagger:
        default-include-pattern: /api/.*
        title: eoffice API
        description: eoffice API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url: