logging:
  level:
    #ROOT: INFO
    org.springframework.web : DEBUG
    org.springframework.security : DEBUG
    org.springframework.boot.autoconfigure.security.oauth2: DEBUG
    org.springframework.cloud.netflix: DEBUG
    
server:
  port: 8083
  servlet:
    session:
      cookie:
        http-only: true

spring:
  application:
    name: eoffice-qn-api-vanbanden
  jmx:
    default-domain: eoffice-qn-api-vanbanden
  mvc:
    favicon:
      enabled: false
  main.allow-bean-definition-overriding: true
  autoconfigure:
      exclude: 
          - org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration
          - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration
          - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env", "health", "info", "threaddump", "logfile", "jhi-metrics", "prometheus" ]
  endpoint:
    health:
      show-details: when-authorized
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    enable:
      jvm: true
      processor: true
      uptime: true
      logback: true
      files: true
      integration: true
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    web:
      server:
        auto-time-requests: true
        
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    appname: eoffice-qn-api-vanbanden
    instanceId: eoffice-qn-api-vanbanden:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: ${info.project.version:}
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}

feign:
  client: #point to [gateway-host]:[gateway-port]/[service-path-defined-in-gateway]
    location:
      gateway: https://dev-api-qn.eoffice.greenglobal.vn
      #gateway: http://localhost:8080
      danh-muc.url: ${feign.client.location.gateway}/danh-muc/api/client
      he-thong.url: ${feign.client.location.gateway}/he-thong/api/client
                     
security:
  oauth2:
    client: #SP eoffice-local
      clientId: TajdoYxTyZI8XexKgnZnS3corK0a  
      clientSecret: 7vCJR0hUi8EVYh8ULNp0FfqrmiEa
      scope:
      - openid
      - profile
    resource:
      user-info-uri: https://sso.lgsp.greenglobal.vn/oauth2/userinfo?schema=openid
      
