spring:
  profiles:
    active: h2
  liquibase:
    enabled: false
    change-log: classpath:/migrations/h2/master.xml
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:~/data/eoffice/h2/uaa;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS uaa
    username: sa
    password: sa
    hikari:
      poolName: uaa-pool
      maximum-pool-size: 2
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 60000
      auto-commit: false
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  elasticsearch:
    rest:
      uris:
      - https://es.eoffice.greenglobal.vn
      username: elastic
      password: changeme
    index:
      name: 'nguoidung_1.1'
      alias: 'nguoidung'
      type: 'doc'
      shard: 3
      replica: 2
      from: 0
      size: 10
      timeout: 60
feign:
  client: #point to [gateway-host]:[gateway-port]/[service-path-defined-in-gateway]
    location:
      gateway: https://dev-api-qn.eoffice.greenglobal.vn
      #gateway: http://localhost:8080
      danh-muc.url: localhost:8081/api/client
      he-thong.url: localhost:8082/api/client