# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
    port: 8082
    
logging:
    level:
        ROOT: INFO
        vn.tcx.framework: DEBUG
        vn.tcx.eoffice.user: DEBUG
    
spring:
    profiles:
        active: h2
        #include:
        #    - swagger
            # Uncomment to activate TLS for the dev profile
            #- tls
    jackson:
        serialization:
            indent-output: true
    liquibase:
        enabled: false
        change-log: classpath:/migrations/h2/master.xml
    h2:
        console:
            enabled: true
    datasource:
        driver-class-name: org.h2.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:~/data/eoffice/h2/uaa;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS uaa
        username: sa
        password: sa
        hikari:
            poolName: uaa-pool
            maximum-pool-size: 2
            connection-test-query: SELECT 1 FROM DUAL
            connection-timeout: 60000
            auto-commit: false
            
    jpa:
        hibernate:
            ddl-auto: none
        #database-platform: org.hibernate.dialect.Oracle12cDialect
        # database: ORACLE
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            #hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            #hibernate.cache.hazelcast.instance_name: common
            #hibernate.cache.use_minimal_puts: true
            #hibernate.cache.hazelcast.use_lite_member: true
    #data:
    #    jest:
    #        uri: http://localhost:9200
    elasticsearch:
      rest:
        uris:
        - https://es.eoffice.greenglobal.vn
        username: elastic
        password: changeme

tcx:
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        
elasticearch:
  index:
    name: 'uaa_1.1'
    alias: 'uaa'
    type: 'doc'
    shard: 3
    replica: 2
    from: 0
    size: 10
    timeout: 60
    
wso2.check-user: http://192.168.1.200:8090/isExistingUser?userName=
