# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  profiles:
      active: live
        #include:
        #    - swagger
            # Uncomment to activate TLS for the dev profile
            #- tls
  liquibase:
    enabled: false
    change-log: classpath:/migrations/master.xml
  kafka:
    producer:
        topics: notifications-live
        bootstrap-servers: 10.255.35.20:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: vn.tcx.eoffice.lichcongtac.stream.NotificationSerializer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@10.255.45.12:1521:xe
    username: lichcongtac
    password: Eoffqn1234
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      poolName: lichcongtac-pool
      auto-commit: false
  jpa:
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      #hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      #hibernate.cache.hazelcast.instance_name: common
      #hibernate.cache.use_minimal_puts: true
      #hibernate.cache.hazelcast.use_lite_member: true
  elasticsearch:
    rest:
      uris:
      - http://10.255.25.11:9200
      username: elastic
      password: changeme
    index:
      alias: 'qoffice_stag_lichcongtac'
      type: 'doc'
      shard: 3
      replica: 2
      from: 0
      size: 10
      timeout: 60
    time:
      timeZoneId: 'UTC+7'

security:
  #byPassApiSecure: false
  oauth2:
    spGroup: Application/eoffice-live
    client: # SP eoffice-test2
      clientId: eqaR_x5qvVawWeKyfH8ZEVZ8utUa
      clientSecret: q5atJMH8QpHc0PWyQbsyPfsDpvwa
    resource:
      user-info-uri: https://sso.lgsp.quangnam.gov.vn/oauth2/userinfo?schema=openid

tcx:
    errbit:
        host: http://10.255.35.21:8088/notifier_api/v2/notices
        id: 1
        key: e0e5b65440442185e09f19e522835097
        env: live

feign:
  client: #point to [gateway-host]:[gateway-port]/[service-path-defined-in-gateway]
    location:
      gateway: http://api-qoffice.quangnam.gov.vn
      #gateway: http://localhost:8080
      danh-muc.url: ${feign.client.location.gateway}/danh-muc/api/client
      he-thong.url: ${feign.client.location.gateway}/he-thong/api/client
      #he-thong.url: http://localhost:8082/api/client
      #danh-muc.url: http://localhost:8081/api/client
      ho-so-cong-viec.url: ${feign.client.location.gateway}/ho-so-cong-viec/api/client
      file.url: http://file-qoffice.quangnam.gov.vn/api
