spring:
    profiles:
        active: stag
        #include:
        #    - swagger
            # Uncomment to activate TLS for the dev profile
            #- tls
    liquibase:
        enabled: false
        change-log: classpath:/migrations/master.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:oracle:thin:@10.255.45.15:1521:xe
        username: common
        password: Eoffqn12345
        hikari:
            poolName: danhmuc-pool
            auto-commit: false
    jpa:
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            #hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            #hibernate.cache.hazelcast.instance_name: common
            #hibernate.cache.use_minimal_puts: true
            #hibernate.cache.hazelcast.use_lite_member: true
    elasticsearch:
      rest:
        uris:
        - http://10.255.25.11:9200
        username: elastic
        password: changeme
      index:
        alias: 'qoffice_staging_coquanbanhanh'
        type: 'doc'
        shard: 3
        replica: 2
        from: 0
        size: 10
        timeout: 60

security:
  byPassApiSecure: false
  oauth2:
    spGroup: Application/eoffice-stag
    client: # SP eoffice-stag
      clientId: YRNBGL7NOmIuWZklZLQDnmfBvqMa
      clientSecret: 7bGWOGE8_c1RZs9JNCfINIgQaz8a
    resource:
      user-info-uri: https://sso.lgsp.quangnam.gov.vn/oauth2/userinfo?schema=openid
      
tcx:
    errbit:
        host: http://10.255.35.21:8088/notifier_api/v2/notices
        id: 1
        key: 51eb081b528ccae712b3241994ab091f
        env: stag

feign:
  client:
    location: 
      gateway: https://api-qoffice-staging.quangnam.gov.vn
      